### ISSUE TITLE
Add Japan series data

### ISSUE THREAD

**Issue by nogic1008** [ddradar/consumer-ddr#105]
## ~~PlayStation 2~~
- [x] DDRMAX (#620)
- [x] DDRMAX2 (#629)
- [x] Dance Dance Revolution EXTREME (#639)
- [x] Dance Dance Revolution Party Collection (#641)
- [x] Dance Dance Revolution FESTIVAL (#644)
- [x] Dance Dance Revolution STR!KE (#646)
- [x] Dance Dance Revolution SuperNOVA (#712)
- [x] Dance Dance Revolution SuperNOVA 2 (#732)
- [x] Dance Dance Revolution X (#734)
## Wii
- [x] Dance Dance Revolution HOTTEST PARTY (#738)
- [x] Dance Dance Revolution フルフルパーティー (#747)
- [x] Dance Dance Revolution MUSIC FIT (#748)
## ~~PlayStation~~
- [x] Dance Dance Revolution
- [x] Dance Dance Revolution 2nd ReMIX
- [x] Dance Dance Revolution 3rd MIX
- [x] Dance Dance Revolution BEST HITS
- [x] Dance Dance Revolution EXTRA MIX (#622)
- [x] Dance Dance Revolution 4th MIX (#618)
- [x] Dance Dance Revolution 5th MIX (#624)
- [x] Dance Dance Revolution 2nd ReMIX APPEND CLUB VERSION vol.1
- [x] Dance Dance Revolution 2nd ReMIX APPEND CLUB VERSION vol.2
- [x] Dancing Stage featuring TRUE KiSS DESTiNATiON
- [x] Dancing Stage featuring DREAMS COME TRUE
- [x] Dance Dance Revolution Disney's RAVE
- [x] Dance Dance Revolution おはスタ (#619)
## ~~Dreamcast~~ #52
- [x] Dance Dance Revolution 2nd MIX Dreamcast Edition
- [x] Dance Dance Revolution CLUB Ver Dreamcast Edition
## ~~GAME BOY~~ #59 
- [x] Dance Dance Revolution GB
- [x] Dance Dance Revolution GB2
- [x] Dance Dance Revolution GB3
- [x] おはスタ Dance Dance Revolution GB
- [x] Dance Dance Revolution GB Disney Mix
