### ISSUE TITLE
Create Song Page

### ISSUE THREAD

**Issue by nogic1008** [ddradar/consumer-ddr#33]
## Tasks
- [x] Repository `/plugins/song-repository.ts`
- [x] List Page `/song/index.vue`
- [x] Detail Page `/song/_songId/index.vue`
- [x] Add generate option
