### ISSUE TITLE
Add DDR GRAND PRIX data

### ISSUE THREAD

**Issue by nogic1008** [ddradar/consumer-ddr#737]
- [x] FREE play (#761)
- [x] GRAND PRIX play (#761)
- [x] GRAND PRIX Song Pack Vol.1 (#761)
- [x] GRAND PRIX Song Pack Vol.2 (#767)
- [x] GRAND PRIX Song Pack Vol.3 (#772)
- [x] GRAND PRIX Song Pack Vol.4 (#779)
- [ ] GRAND PRIX Song Pack Vol.5 (#781)
- [ ] GRAND PRIX Song Pack Vol.6 (#781)
- [ ] GRAND PRIX Song Pack Vol.7 (#781)
- [ ] GRAND PRIX Song Pack Vol.8 (#781)
- [ ] GRAND PRIX Song Pack Vol.9 (#781)
- [ ] GRAND PRIX Song Pack Vol.10 (#781)
- [ ] GRAND PRIX Song Pack Vol.11 (#781)
- [ ] GRAND PRIX Song Pack Vol.12 (#781)
- [ ] GRAND PRIX Song Pack Vol.13 (#781)
- [ ] GRAND PRIX Song Pack Vol.14 (#781)
- [ ] GRAND PRIX Song Pack Vol.15 (#781)
- [ ] GRAND PRIX Song Pack Vol.16 (#781)
- [x] Controller (#779)
- [x] Special Music Pack feat. jubeat Vol.1 (#770)
- [x] Special Music Pack feat. jubeat Vol.2 (#770)
- [x] Special Music Pack feat. Touhou Project Vol.1 (#772)
- [x] Special Music Pack feat. Touhou Project Vol.2 (#772)
